name: Autograding Tests
'on':
  - push
  - workflow_dispatch
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # Use the mempool folder already present in this repository
      - name: Prepare grader inputs
        run: |
          set -euxo pipefail
          mkdir -p code-challenge-2024-mempool
          # Provide mempool directory where the grader expects it
          if [ -d mempool ]; then
            rm -rf code-challenge-2024-mempool/mempool || true
            cp -R mempool code-challenge-2024-mempool/mempool
          fi
          # Provide valid-mempool.json from local cache if available
          if [ -f valid_txn_cache.json ]; then
            cp valid_txn_cache.json code-challenge-2024-mempool/valid-mempool.json
          fi
      - name: Validate block
        id: validate-block
        uses: SummerOfBitcoin/code-challenge-2024-grader@v2.8
        with:
          test-name: 'Validate block '
          command: chmod +x ./run.sh && ./run.sh
          timeout: 10
          max-fee: 20616923
          max-score: 100
          passing-score: 60
      - name: Autograding Reporter
        uses: SummerOfBitcoin/autograding-grading-reporter@v2.2
        env:
          VALIDATE-BLOCK_RESULTS: "${{steps.validate-block.outputs.result}}"
        with:
          runners: validate-block
